### ISSUE TITLE
tests failing with latest engine.io

### ISSUE THREAD

**Issue by cayasso** [carlos8f/engine.oil#2]
Does this module work with latest engine.io and engine.io-client ? 

Tests are failing.

JB

**Comment by carlos8f** [comment]
I have only tested with engine.io 0.2.x, and 0.4.x definitely reorganized some stuff. eio.EventEmitter was renamed to eio.Emitter, and I fixed that in the new [eio-0.4 branch](https://github.com/carlos8f/engine.oil/tree/eio-0.4). I don't have time to fix everything right now though, pull requests welcome :)

**Comment by carlos8f** [comment]
hi, I pushed some new commits (and published v0.4.0) that upgrade engine.io to 0.6, and the tests appear to be working (except zombie.js apparently can't handle upgrade:false option). Please let me know if it works for you or doesn't!

Cheers

**Comment by cayasso** [comment]
Awesome man, I will take a look at soon as I have a chance.

Best,

JB
